from __future__ import annotations

import unittest
from pathlib import Path

from frontmatter import frontmatter_for


ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT / "gonol-build" / "SKILL.md"
ADAPTER = ROOT / "skills" / "gonol-build" / "SKILL.md"
WITNESS = ROOT / "tools" / "check_gonol_authority.py"


class GonolBuildSkillTest(unittest.TestCase):
    def setUp(self) -> None:
        self.text = SKILL.read_text(encoding="utf-8")
        self.compact = " ".join(self.text.split())
        self.frontmatter = frontmatter_for(SKILL)

    def test_activation_contract_is_concrete(self) -> None:
        description = self.frontmatter["description"]
        for phrase in (
            "UCNS gonol objects",
            "Stack owns active construction research",
            "EDCM owns measurement/evaluation only",
            "no universal adjacent-scale ladder is required",
            "Pronunciation is not required",
        ):
            self.assertIn(phrase, description)

    def test_authority_split_is_current(self) -> None:
        for phrase in (
            "UCNS = gonol objects, constructors, and underlying geometry",
            "Stack = active language-gonol construction research workspaces",
            "EDCM = measurement and evaluation of constructed outputs",
            "skill-lib = construction/replay discipline",
        ):
            self.assertIn(phrase, self.compact)
        self.assertNotIn("EDCM = text-domain gonol construction", self.compact)
        self.assertNotIn("EDCM owns the admissible scale options", self.compact)

    def test_active_construction_resolves_stack_workspace(self) -> None:
        self.assertIn("research/english-gonol/", self.text)
        self.assertIn("research/python-gonol/", self.text)
        self.assertIn("Do not start in EDCM", self.text)
        self.assertIn("Historical EDCM constructor names", self.text)

    def test_gonol_object_authority_remains_ucns(self) -> None:
        for phrase in (
            "Consume UCNS gonol constructors and geometry",
            "Defining a competing gonol object",
            "consume UCNS construction authority",
        ):
            self.assertIn(phrase, self.compact)

    def test_closed_gonols_participate_atomically(self) -> None:
        for phrase in (
            "Any closed gonol is atomic at an admissible consuming scale",
            "constituent identities, order, multiplicity, source positions, relations, and provenance remain recoverable",
            "Constitutive relationships belong inside the construction",
            "Recursive relations consume already-closed gonols",
        ):
            self.assertIn(phrase, self.compact)

    def test_no_substitute_representation(self) -> None:
        for phrase in (
            "Do not normalize, deduplicate, infer relations",
            "tokens, AST nodes, compiler objects, embeddings, hashes, or metadata",
            "do not fill it with an invented rule",
        ):
            self.assertIn(phrase, self.compact)

    def test_local_authority_gate_is_named(self) -> None:
        self.assertTrue(WITNESS.is_file())
        self.assertIn("python tools/check_gonol_authority.py", self.text)

    def test_completion_preserves_replay_boundary(self) -> None:
        for phrase in (
            "preflight the resources required to finish it",
            "Do not add arbitrary wall-clock limits",
            "the complete declared source scope",
            "deterministic construction receipts",
            "independent complete replay where replay is required",
            "Replay establishes reproducibility of that construction only",
        ):
            self.assertIn(phrase, self.compact)

    def test_codex_adapter_points_to_canonical_skill(self) -> None:
        text = ADAPTER.read_text(encoding="utf-8")
        self.assertIn("Generated by tools/build_codex_plugin_skills.py", text)
        self.assertIn("../../gonol-build/SKILL.md", text)
        self.assertIn("EDCM owns measurement/evaluation only", text)
        self.assertNotIn("EDCM owns text construction", text)


if __name__ == "__main__":
    unittest.main()
